sources:
  nginx_logs:
    type: file
    include: ["/var/log/nginx/access.log"]
    ignore_older_secs: 600

sinks:
  to_victorialogs:
    type: http
    inputs: [nginx_logs]
    uri: http://victorialogs:9428/insert/jsonline
    encoding:
      codec: text # Передаем как текст, VL сам разберется