events {
    worker_connections 1024;
}

http {
    log_format json_combined escape=json
      '{"time_local":"$time_local",'
      '"client_ip":"$remote_addr",'
      '"request":"$request",'
      '"status": "$status",'
      '"body_bytes_sent":"$body_bytes_sent",'
      '"http_user_agent":"$http_user_agent"}';

    access_log /var/log/nginx/access.log json_combined;

    server {
        listen 80;
        
        location / {
            return 200 "Hello from Nginx! Writing pure JSON now.\n";
        }
    }
}